---
- name: Install GitLab
  become: True
  roles:
    - role: "../roles/gitlabservers"
  hosts: gitlabservers
  vars:
    pip_install_packages:
      - name: docker-compose
    docker_users:
      - ubuntu